export const WORKSPACE_PAGE_CHANGE = Symbol('USERINFO_LOGIN_CHANGE');
export const WORKSPACE_SIDEBAR_AREA_CHANGE = Symbol('WORKSPACE_SIDEBAR_AREA_CHANGE');
export const WORKSPACE_SIDEBAR_IDX_CHANGE = Symbol('WORKSPACE_SIDEBAR_IDX_CHANGE');
export const WORKSPACE_SIDEBAR_IDX_AREA = Symbol('WORKSPACE_SIDEBAR_IDX_CHANGE');
export const WORKSPACE_SIDEPAGE_CHANGE = Symbol('WORKSPACE_SIDEPAGE_CHANGE');
export const WORKSPACE_SIDEPAGE_NAME = Symbol('WORKSPACE_SIDEPAGE_NAME');
export const WORKSPACE_CURRENT_ITEM_KEY = Symbol('WORKSPACE_CURRENT_ITEM_KEY');
export const WORKSPACE_SIDEMENU_PAGEIDX = Symbol('WORKSPACE_SIDEMENU_PAGEIDX');
